### ISSUE TITLE
Concatenation sign on AlphaNamesValidator

### ISSUE THREAD

**Issue by emmurd** [micheleangioni/phalcon-validators#1]
Hi,

there's a little mistake on line 35 and 39 of the file AlphaNamesValidator.php. It use the concatenation sign "+" instead of the "." sign. If no custom message is passed, it make my api crash.

Thanks for looking into that matters.

**Comment by micheleangioni** [comment]
Hi,
thanks for reporting this bug. I have just fixed it in the new 1.5.1 release.
Please let me know if you discover other bugs or experience problems.

Best Regards
